on:
  schedule:
    - cron: "0 10 * * *" 
    - cron: "0 22 * * *" 
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping App
        run: curl -s -o /dev/null -w "%{http_code}" https://cartolaturnos.streamlit.app/
